### ISSUE TITLE
Gralha no registo: https://pesquisa.auc.uc.pt/details?id=220198

### ISSUE THREAD

**Issue by joaquimrcarvalho** [joaquimrcarvalho/fauc1537-1919#1]
**Identificação do registo**

https://pesquisa.auc.uc.pt/details?id=220198

**Correção**

Gralha na quinta matrícula
0110.1686 -> 01.10.1686
-----

Nível de descrição
 Documento simples   Documento simples
Código de referência
PT/AUC/ELU/UC-AUC/B/001-001/S/003510
Tipo de título
Atribuído
Título
Manuel dos Santos
Datas de produção
1681-10-01   a  1688-02-17  
História administrativa/biográfica/familiar
Filiação: Manuel Fernandes
Naturalidade: Évora
Âmbito e conteúdo
Faculdade: Leis
Matrícula(s): 01.10.1682
10.11.1683
01.10.1684
01.10.1685
#### 0110.1686 -> 01.10.1686
01.10.1686
01.10.1687
Instituta: 01.10.1681
Bacharel 21.07.1687
Formatura 17.02.1688
Data de publicação
14/05/2021 11:52:41

-----

**Comment by catarinamacedo** [comment]
Corrigi
