### ISSUE TITLE
Gralha faculdade Leis em vez de Medicina https://pesquisa.auc.uc.pt/details?id=190616

### ISSUE THREAD

**Issue by joaquimrcarvalho** [joaquimrcarvalho/fauc1537-1919#10]
**Identificação do registo**

1. Localize o registo no "Índice de alunos da Universidade de Coimbra"
2. Anote o url do registo na linha abaixo

https://pesquisa.auc.uc.pt/details?id=190616
Afonso Rodrigues

Este registo tem Faculdade: Leis mas todas as referências internas são a Medicina.
O campo faculdade deve ser alterado para "Medicina"

**Correção**

3. Copie o conteúdo central do registo, desde "Código de referência" até "Data de publicação"
4. Corrija o erro
5. Antes da alteração insira uma linha começada por #### assinalando o que foi alterado
-----

Código de referência
PT/AUC/ELU/UC-AUC/B/001-001/R/003012
Tipo de título
original
Título
Afonso Rodrigues
Datas de produção
1538-05-02   a  1556-05-01  
Extensões
0 Álbum
História administrativa/biográfica/familiar
Filiação:
Naturalidade: Beja
Âmbito e conteúdo
### Faculdade: Leis -> Faculdade: Medicina
Faculdade: Medicina
Matrícula(s): 1538.05.02
## Examepara bacharel... -> Exame para bacharel...
Exame para bacharel corrente em Medicina e grau de Bacharel 1555.06.30 A.Nemine
Provou ter o tempo que se requer para se fazer bacharel em artes 1551
1 cursou em Medicina de 1552 a 1553. provou que ? medicina desde outubro de 1553 a 1554.17.31. cursou em medicina que acaba em 1556.05.01
Bacharel em artes 1551.02.24
Licenciado em artes 1552.04.30
Mestre em artes 1552.
Instituta :
Idioma e escrita
Português
Data de publicação
04/02/2021 15:06:14

-----

 **Não se esqueça de colocar o URL do registo no título**

**Comment by catarinamacedo** [comment]
Corrigi
