### ISSUE TITLE
Verificar registo Abel Maria Jordão https://pesquisa.auc.uc.pt/details?id=193254

### ISSUE THREAD

**Issue by joaquimrcarvalho** [joaquimrcarvalho/fauc1537-1919#13]
**Identificação do registo**

URL:  https://pesquisa.auc.uc.pt/details?id=193254
Abel Maria Jordão

Este estudante é certamente  *Abel Maria Jordão de Paiva Manso* 
(https://pt.wikipedia.org/wiki/Abel_Maria_Jordão_Paiva_Manso)

Aparece aliás no ficheiro como pai, com o nome completo:
https://pesquisa.auc.uc.pt/details?id=193376

**Problema**

História administrativa/biográfica/familiar
Filiação: Francisco António Jordão
__Naturalidade: Buarcos__ <---

**O que necessita de ser verificado**

Naturalidade: deveria ser Coimbra ver https://gw.geneanet.org/aqf?lang=fr&n=manso&oc=0&p=abel+maria+jordao+de+paiva

Ver na ficha em papel se está efectivamente "Buarcos".

**Comment by joaquimrcarvalho** [comment]
Se está na ficha Buarcos é melhor ficar apenas Buarcos, como estava. Em caso de discordância com outras fontes vale o que está na ficha do AUC até melhor verificação documental ser possível.

**Comment by catarinamacedo** [comment]
Corrigi
