### ISSUE TITLE
Verificar remissiva em falta no registo https://pesquisa.auc.uc.pt/details?id=128114

### ISSUE THREAD

**Issue by joaquimrcarvalho** [joaquimrcarvalho/fauc1537-1919#28]
Registo: https://pesquisa.auc.uc.pt/details?id=128114
**Identificação do registo**

1. Localize o registo no "Índice de alunos da Universidade de Coimbra"
2. Anote o url do registo na linha abaixo

https://pesquisa.auc.uc.pt/details?id=128114
Belchior de Sá Cabral

**Correção**
CORRIGIR: Falta vide
Esta ficha dever ser uma remissiva para "Belchior de Sá" https://pesquisa.auc.uc.pt/details?id=211581.  

Verificar no original.

Se sim acrescentar a expressão ", vide Sá"  ao nome

-----

Id: 128114
Código de referência: PT/AUC/ELU/UC-AUC/B/001-001/C/000151

# Adicionar vide
Nome        : Belchior de Sá Cabral, vide Sá
Data inicial: 0000-00-00
Data final  : 0000-00-00
Naturalidade: Alfândega
Faculdade: Cânones

**Comment by catarinamacedo** [comment]
Corrigi
