### ISSUE TITLE
Verificar data truncada https://pesquisa.auc.uc.pt/details?id=140341 

### ISSUE THREAD

**Issue by joaquimrcarvalho** [joaquimrcarvalho/fauc1537-1919#3]
**Identificação do registo**

1. Localize o registo no "Índice de alunos da Universidade de Coimbra"
2. Anote o url do registo na linha abaixo

URL: 
https://pesquisa.auc.uc.pt/details?id=140341

Francisco Xavier Abelha
PT/AUC/ELU/UC-AUC/B/001-001/A/000005

** Conteúdo atual **

> Atual:

Instituta: 01.10.1729
Bacharel: 15.05.1735
Formatura: 16.07.17 

> O que necessita de ser verificado

Instituta: 01.10.1729
Bacharel: 15.05.1735
Formatura: 16.07.17  <-- data de formatura

 ** Não se esqueça de colocar o URL do registo no título **

**Comment by catarinamacedo** [comment]
Corrigi
