### ISSUE TITLE
Gralha no registo: https://pesquisa.auc.uc.pt/details?id=139558

### ISSUE THREAD

**Issue by joaquimrcarvalho** [joaquimrcarvalho/fauc1537-1919#30]
Gralha no Registo: https://pesquisa.auc.uc.pt/details?id=139558
**Identificação do registo**

1. Localize o registo no "Índice de alunos da Universidade de Coimbra"
2. Anote o url do registo na linha abaixo

https://pesquisa.auc.uc.pt/details?id=139558
António da Fonseca

**Correção**
CORRIGIR: pontuação em Instituta

-----

Id: 139558
Código de referência: PT/AUC/ELU/UC-AUC/B/001-001/F/005719

Nome        : António da Fonseca
Data inicial:
Data final  :
Filiação:
Naturalidade: Braga
Faculdade:

Matrícula(s):
#### Pontuação
Instituta: 01.11.1561 até 10.05.1563

**Comment by catarinamacedo** [comment]
Corrigi
