### ISSUE TITLE
Verificar registo https://pesquisa.auc.uc.pt/details?id=176676  António de Carvalho Pinto Osório

### ISSUE THREAD

**Issue by joaquimrcarvalho** [joaquimrcarvalho/fauc1537-1919#32]
Este formulário serve para registar problemas que 
poderão ser resolvidos consultando a ficha original
no catálogo manual.

URL: 
https://pesquisa.auc.uc.pt/details?id=176676  
António de Carvalho Pinto Osório

**Problema**

Naturalidade: Valença do Douro, Trancoso

**O que necessita de ser verificado**

Valença do Douro é uma freguesia do concelho de __Tabuaço__

Verificar na ficha se está Trancoso ou Tabuaço

**Comment by catarinamacedo** [comment]
Não estava na ficha, retirei e deixei apenas "Valença do Douro"
